version: '3'

services:

  backend:
    build:
      context: ./app/db_init
      dockerfile: Dockerfile
    container_name: docker-backend_php
    ports:
      - "80:80"
    volumes:
      - ./app/templates:/var/www/html
      - ./app/model_app:/var/www/html/model_app
      - ./app/outputs/:/var/www/html/outputs
      - ./app/outputs/Prediction_store1.png
    depends_on:
      - db
      - python_api
    networks:
      app_network:
        aliases:
          - 'backend_host'

  db:
    image: mysql:8.0
    container_name: docker-db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "william"
      MYSQL_DATABASE: forms
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./app/db_init:/docker-entrypoint-initdb.d
      - ./app/db:/var/lib/mysql
    networks:
      app_network:
        aliases:
          - 'mysql_host'
  
  python_api:
    build: 
      context: ./app/model_app
      dockerfile: Dockerfile
    container_name: docker-python_api
    ports:
      - "5000:5000"
    volumes:
      - ./app/model_app:/usr/src/app
    networks:
      app_network:
        aliases:
          - 'pyapp_host'

volumes:
  templates: {}
  model_app: {}
  outputs: {}
  db: {}

networks:
  app_network:
    name: app_net
    driver: bridge
    ipam:
      driver: default

  


  